kafka_user: neverwinterdp
kafka_group: neverwinterdp

kafka_home_dir: /opt/kafka/
kafka_data_dir: /data/kafka-logs/

#kafka_tgz_url: 'https://s3-us-west-2.amazonaws.com/nvent-repo/tgz/kafka/0.8.2.1/kafka_2.10-0.8.2.1.tgz'
#kafka_tgz_url: http://jenkinsdp.do.demandcube.com/kafka_2.10-0.8.2.0.tgz
kafka_tgz_url: http://mirror.ox.ac.uk/sites/rsync.apache.org/kafka/0.8.2.2/kafka_2.10-0.8.2.2.tgz
#kafka_tgz: kafka_2.10-0.8.2.1.tgz
#kafka_dir: kafka_2.10-0.8.2.1

zookeeper_connect: 'zookeeper-1:2181'

kafka_port: 9092
advertised_port: 9092
num_network_threads: 8
num_io_threads: 8
socket_send_buffer_bytes: 1048576
socket_receive_buffer_bytes: 1048576
socket_request_max_bytes: 104857600
replica_fetch_max_bytes: 2500000
message_max_bytes: 2500000
log_flush_interval_messages: 10000
log_flush_interval_ms: 1000
log_retention_hours: 168
log_segment_bytes: 536870912
log_retention_check_interval_ms: 60000
log_cleaner_enable: true
zookeeper_connection_timeout_ms: 1000000
auto_create_topics_enable: true
default_replication_factor: 3
