#- include: ../../../programs/wget.yml
- include: ../../../programs/nano.yml
#- include: ../../../programs/git.yml
#- include: ../../../programs/bc.yml
#- include: ../../../programs/vim.yml
#- include: ../../../programs/openssh.yml


- include: ../../../programs/epel.yml
  tags:
    - install

- include: ../../../programs/rsync.yml
  tags:
    - install

- include: ../../../programs/pip.yml
  tags:
    - install

- include: ../../../programs/openjdk7_java.yml
  tags:
    - install

- include: ../../../programs/sshkeys.yml
  tags:
    - install

- include: ../../../programs/lsof.yml
  tags:
    - install
    
- include: ../../aws_credentials/tasks/main.yml
  tags:
    - install

- include: ../../../programs/libffi.yml
  tags:
    - install

- include: ../../../programs/npm.yml
  tags:
    - install

- include: ../../../programs/python_devel.yml
  tags:
    - install

- include: ../../../programs/commander_dependencies.yml
  tags:
    - install

#- include: ../../increase_open_file_limit/tasks/main.yml
#  tags:
#    - install

