- include: ../../../programs/wget.yml
#- include: ../../../programs/nano.yml
#- include: ../../../programs/git.yml
#- include: ../../../programs/bc.yml
#- include: ../../../programs/vim.yml
#- include: ../../../programs/openssh.yml

- include: ../../../programs/epel.yml
- include: ../../../programs/rsync.yml
- include: ../../../programs/pip.yml
- include: ../../../programs/openjdk7_java.yml
- include: ../../../programs/sshkeys.yml
- include: ../../aws_credentials/tasks/main.yml
- include: ../../../programs/libffi.yml
- include: ../../../programs/npm.yml

