kafka_home_dir: /opt/kafka/
kafka_conf_dir: /opt/kafka/config

KAFKA_HEAP_OPTS: -Xmx1G -Xms1G
zookeeper_clientport: 2181 

# SERVER PROPERTIES
port: 9092

num_network_threads: 2
num_io_threads: 8
socket_send_buffer_bytes: 1048576
socket_receive_buffer_bytes: 1048576
socket_request_max_bytes: 104857600
log_dirs: /opt/kafka/data
num_partitions: 10
num_recovery_threads_per_data_dir: 1
log_retention_hours: 168
log_segment_bytes: 536870912
log_retention_check_interval_ms: 60000
log_cleaner_enable: 'false'
zookeeper_connection_timeout_ms: 1000000
# NOTE: properties below are commented in template/server.properties.j2 
# which kafka taking the default value. 
# if you modify the below properties you need to uncomment 
# corresponding property in template/server.properties.j2
host_name: localhost
advertised_host_name: <hostname routable by clients>
advertised_port: <port accessible by clients>
log_retention_bytes: 1073741824
log_flush_interval_messages: 10000
log_flush_interval_ms: 1000

# CONSUMER PROPERTIES
zookeeper_connection_timeout_ms: 1000000
group_id: neverwinterdp
# NOTE: properties below are commented in template/consumer.properties.j2 
# which kafka taking the default value. 
# if you modify the below properties you need to uncomment 
# corresponding property in template/consumer.properties.j2
consumer_timeout_ms: 5000

# PRODUCER PROPERTIES
producer_type: sync
compression_codec: none
serializer_class: kafka.serializer.DefaultEncoder
# NOTE: properties below are commented in template/producer.properties.j2 
# which kafka taking the default value. 
# if you modify the below properties you need to uncomment 
# the corresponding property in template/producer.properties.j2
partitioner_class: 
compressed_topics: 
queue_buffering_max_ms: 
queue_buffering_max_messages: 
queue_enqueue_timeout_ms: 
batch_num_messages: 



